use std::fs;
use std::path::PathBuf;

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root")
        .to_path_buf()
}

fn read(relative: &str) -> String {
    fs::read_to_string(workspace_root().join(relative))
        .unwrap_or_else(|err| panic!("failed to read {relative}: {err}"))
}

#[test]
fn calculation_runtime_queries_no_longer_allocate_ids_manually() {
    let content = read("astral_calculator/src/infra/db/runtime_queries/calculation.rs");

    for forbidden in ["next_id(", "LOCK TABLE", "MAX(id)"] {
        assert!(
            !content.contains(forbidden),
            "calculation runtime queries still contain forbidden manual id allocator marker {forbidden}"
        );
    }
}

#[test]
fn importer_keeps_runtime_tables_identity_backed() {
    let importer = read("scripts/import_json_db_to_postgres.py");

    assert!(
        importer.contains("generated by default as identity"),
        "importer must provision identity-backed runtime ids"
    );

    for table_name in [
        "astral_chart_calculations",
        "astral_calculated_house_cusps",
        "astral_calculated_chart_object_positions",
        "astral_calculated_aspects",
        "astral_interpretation_signals",
        "astral_interpretation_generation_payloads",
    ] {
        assert!(
            importer.contains(&format!("\"{table_name}\"")),
            "importer identity table list is missing {table_name}"
        );
    }
}
